# Generated by Django 3.2.7 on 2021-09-21 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=128, verbose_name='Отчество')),
                ('post', models.CharField(max_length=255, verbose_name='Должность')),
                ('post_type', models.CharField(choices=[('MN', 'Manager'), ('SB', 'Subordinate')], max_length=20, verbose_name='Тип должности')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
