# Generated by Django 3.2.7 on 2021-09-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_department_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighLevelDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Подразделение')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Отдел')),
                ('high_level_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.highleveldepartment', verbose_name='Кому подчиняется')),
            ],
            options={
                'verbose_name': 'Схема подчинения',
            },
        ),
    ]
