# Generated by Django 3.2.7 on 2021-09-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_departmentrelations_highleveldepartment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentrelations',
            options={'verbose_name': 'Схема подчинения', 'verbose_name_plural': 'Схемы подчинения'},
        ),
        migrations.AlterField(
            model_name='department',
            name='level',
            field=models.CharField(blank=True, choices=[('1', '1-й уровень'), ('2', '2-й уровень'), ('3', '3-й уровень'), ('4', '4-й уровень'), ('5', '5-й уровень')], max_length=30, verbose_name='Уровень в организации'),
        ),
    ]
